### ISSUE TITLE
Have `tzdata` depend on `tz`

### ISSUE THREAD

**Issue by lpsmith** [nilcons/haskell-tz#6]
This package looks like a decent start,  but perhaps it would make more sense to have `tzdata` depend on `tz` instead of the other way around,  as it is now.   That way,  it's easy to avoid `tzdata` if you would prefer to use the system timezone files.

**Comment by klao** [comment]
The whole point of `tzdata` being a separate package is so that others could use it (if they didn't want `tz`, but something else, like `timezone-series`). Otherwise the two would have been a single package.

You can still just use the system timezone files, nothing from tzdata will be compiled into your binary if you don't use it.

**Comment by lpsmith** [comment]
> You can still just use the system timezone files,

Right,  I understand that much.

> nothing from tzdata will be compiled into your binary if you don't use it.

Interesting,  how does that work?

**Comment by klao** [comment]
> Interesting, how does that work?

It's nothing special, if you don't reference an object, the linker won't include it.
