### ISSUE TITLE
Strange results with Australia/Brisbane and Asia/Dubai

### ISSUE THREAD

**Issue by glasserc** [nilcons/haskell-tz#8]
At https://github.com/glasserc/weird-tzs I have pushed a test program that demonstrates a strange behavior that we saw in production. It takes the date 2015-11-23 midnight in Brisbane and converts it to UTC. On my machine, its output is:

```
$ cabal run
Preprocessing executable 'weird-tzs' for weird-tzs-0.1.0.0...
Local time:
2015-11-23 00:00:00
reading date is 2015-08-25 12:37:52 UTC
```

Compare with the output if you change Brisbane to Sydney:

```
$ ./dist/build/weird-tzs/weird-tzs
Local time:
2015-11-23 00:00:00
reading date is 2015-11-22 13:00:00 UTC
```

Certain timezones seem to be affected by this. Asia/Dubai is and Asia/Singapore is, but Asia/Baku isn't.

Interestingly, running the same code in the repl behaves correctly:

```
$ cabal repl Main.hs 
Warning: Ignoring 'Main.hs. The whole executable 'weird-tzs' will be built.
(Support for module and file targets has not been implemented yet.)
[...]
[1 of 1] Compiling Main             ( Main.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
Local time:
2015-11-23 00:00:00
reading date is 2015-11-22 14:00:00 UTC
*Main> 
```

Any idea what's going on? This showed up after we switched from tzdata + timezone-series to tzdata + tz.

**Comment by klao** [comment]
Wow, this is weird.

I'm on a short vacation right now, but I'll try to take a look at this as soon as possible!

**Comment by klao** [comment]
OK, I just quickly checked for now if I can reproduce this issue. And, indeed I can. :)
So, I'll hopefully be able to debug this...

**Comment by klao** [comment]
Wow, this was embarrassing. I'll fix the restrictive bounds on dependencies and will push it to hackage soon.

Thanks a lot for the bug report!

**Comment by pjrt** [comment]
@klao Any idea why this worked in the repl? Your change looks really straight forward yet I can't see why it worked in the repl and not the program.

**Comment by klao** [comment]
Sure. The thing is, it was accessing past the end of a vector. And what happens to be there depends on how the allocator works and what kind of things does the program allocates, when etc. And, the allocator in a compiled Haskell program works quite differently from the interpreter (mostly because of the optimizations, but the interpreter allocates some additional stuff too).

And so, it works deterministically (mostly?) in both cases, but the comparison in the `localToPOSIX` function swings to the favor of the last element of the vector (valid) in the interpreter, and the one after the last (invalid) when compiled, because the memory immediately after the vector gets different values in the two cases.

**Comment by klao** [comment]
OK, I've decided that it's time to "release" this this package, at least as an alpha. So, I uploaded it to Hackage as 0.1.0.0. It should be available soon. Woo!

Thanks again, guys!
